version: '3'
networks:
  net:
    driver: bridge

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      ELASTICSEARCH_NODE: https://amu.es.ap-northeast-2.aws.elastic-cloud.com
    networks:
      net:
        aliases:
          - backend

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    depends_on:
      - backend
  networks:
    net:
      aliases:
        - frontend
